### PR TITLE
Login update

### PR DESCRIPTION
**Pull request by Antonio256**

### CODE REVIEW

**Comment by Antonio256** [comment]
Hi Peter,

Did you manage to finish the project?

**Comment by peterangusa** [comment]
Not really, but will work on

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Antonio256** [comment]
Great. How far with your Nigeria activity?

**Comment by peterangusa** [comment]
Received a due deligence call yesterday.
I need to have all company documents ready; cert of certificate, Trading license, Corporate company account etc.

Have also started online studies

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Antonio256** [comment]
Keep it rolling. That is the Entrepreneurship world. You are on your way
there.

**Pull request merged**
